### PR TITLE
Add validate_features option for Booster predict

### PR DESCRIPTION
**Pull request by kristiancailer**
@afavaro @jtcho @ylwu 

This is the one and only reason why we're forking xgboost. Online predictions are really slow compared to the current ones otherwise. Hooray.

I would add tests as soon as I figure out 1) where they are and 2) how to run them.

(There's an [old xgboost PR](https://github.com/dmlc/xgboost/pull/2536/files) that attempted to add this option, but it's since been closed. Hooray.) 

cc @elibingham @k-nitesh @garrett-schlesinger

### CODE REVIEW

**Comment by garrett-schlesinger** [comment]
Thank you for prioritizing this, Kristian!

**Comment by jtcho** [comment]
To be clear, am I correct in that this change will speed up online predictions by skipping the feature validation step in `predict`?

Will we ever run into a situation online where the Booster/data's feature names would not be identical?

Otherwise, LGTM.

**Comment by kristiancailer** [comment]
@jtcho, yes, this change speeds up online predictions by skipping feature name validation.

We shouldn't ever run into a situation where the Booster and data feature names will be different since we're doing this feature name validation ourselves [here](https://github.com/Affirm/all-the-things/blob/280cf4033738cb7639c043eb8d7483aa1b10bf5c/ml/affirm/ml/models/parametric_gbm/gbm.py#L772). `assert_feature_ordering_match` is called before predictions are made to ensure that the order of the features in the GBM and in the DataFrame passed in are identical.

**Comment by jtcho** [comment]
Sounds good to me. :) Thanks for the explanation!

**Review by jtcho — APPROVED** [review]

**Review by ylwu — COMMENTED** [review]
Looks good. Is it hard to run upstream tests on this PR?

**Comment by kristiancailer** [comment]
@ylwu, what do you mean by upstream tests?

**Comment by ylwu** [comment]
@airknits the tests run on all dmlc/xgboost PRs, like this one https://github.com/dmlc/xgboost/pull/3316

**Comment by kristiancailer** [comment]
Made a PR to xgboost here: https://github.com/dmlc/xgboost/pull/3323

**Comment by ylwu** [comment]
Thanks! it looks like unit tests from that PR is complaining about trailing whitespaces

**Review by ylwu — APPROVED** [review]

**Pull request merged**
